### ISSUE TITLE
No backend sanitization on slug submission endpoint.

### ISSUE THREAD

**Issue by ghost** [cmdwm/0tr.me#5]
There is no sanitization on the slug submission endpoint, therefore allowing users to inject custom urls to be served by the backend. I suggest using a regex to test all URLs as they are submitted. (such as ` /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i`)

Example:
![image](https://user-images.githubusercontent.com/53976867/229314123-e6f47eaa-4558-4cdc-b048-d40e087e1903.png)

**Comment by cmdwm** [comment]
This has been fixed for a while. Not sure why I forgot to close it - thanks for the help!
